"""Initial revision

Revision ID: 28538631bd38
Revises: 
Create Date: 2022-12-04 18:45:22.359081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28538631bd38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
