"""Added last_scraped column to User model

Revision ID: 2ecf1595dcdf
Revises: 77abaea97188
Create Date: 2022-12-09 23:22:30.372441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ecf1595dcdf"
down_revision = "77abaea97188"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_user", sa.Column("last_scraped", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_user", "last_scraped")
    # ### end Alembic commands ###
