"""Included text on Tweet model

Revision ID: 77abaea97188
Revises: 3e0395cc0374
Create Date: 2022-12-05 18:05:29.414698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77abaea97188"
down_revision = "3e0395cc0374"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_tweet", sa.Column("text", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_tweet", "text")
    # ### end Alembic commands ###
