"""Change id integer fields to big integer

Revision ID: 7a9e8a9689fc
Revises: ce68b7f92503
Create Date: 2022-12-17 16:49:24.405986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a9e8a9689fc"
down_revision = "ce68b7f92503"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column("tb_tweet", "id", type_=sa.BigInteger())
    op.alter_column("tb_user", "twitter_id", type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tb_tweet", "id", type_=sa.Integer())
    op.alter_column("tb_user", "twitter_id", type_=sa.Integer())
    # ### end Alembic commands ###
