"""Create attribute twitter_id in model User

Revision ID: ce68b7f92503
Revises: 2ecf1595dcdf
Create Date: 2022-12-14 22:30:57.809419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce68b7f92503"
down_revision = "2ecf1595dcdf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_user", sa.Column("twitter_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_user", "twitter_id")
    # ### end Alembic commands ###
